### ISSUE TITLE
i just see a loading spinner... ublock origin and librewolf (firefox)

### ISSUE THREAD

**Issue by esbenkc** [apartresearch/aisafetyideas#31]
i just see a loading spinner... ublock origin and librewolf (firefox)

**Comment by agucova** [comment]
I believe this was caused by #29, as it's an attribute access violation on exactly the lines that were changed.

See https://github.com/apartresearch/aisafetyideas/blame/ecf078faba80277ab25450cbdbf2d93b6e77a7b5/src/lib/DataLoader.svelte#L104

**Comment by AlexTMjugador** [comment]
Hi @agucova, thanks for reaching out and sorry for the delay in responding!

The PR you linked to wasn't deployed to production neither at the time this issue was reported or at the time you wrote your comment. However, it should be fine now.
